<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Async and Await</title>
</head>

<body>
    
    <script>
       
        // Await --------------------------------------
        // as a name state , it make the code inside function wait at point where it is called till the remailning code is executing .
        // in below code message 1,2,3 then 5 and then4 at last after all execution is completed.
        // async function test_await() {
        //     console.log("2: Message");
        //     await console.log("3: Message");
        //     console.log("4: Message");
        // }

        // numbering is according to message that will print first.
        // console.log("1: Message");
        // test_await();
        // console.log("5 : Message");



        //------generally we use this method when we are fetching some data from the server so it takes time ,
        //that is why we put that code itno await , so that it can take its time to fetch and our remaining is not interrupt by this.

        async function test() {
                console.log("2: Message");
                const response = await fetch("https://jsonplaceholder.typicode.com/users");
                //fetch function is also return a promise, so to handle promise
                console.log('3: Message')
                
                //now this above promise is handle by this below promise, and we know promise return some result ,accept or reject.
                //that will be stored in students then we will return it too.
                const students = await response.json();

                
                return students;
            }

            // numbering is according to message that will print first.
            console.log("1: Message");
            
            //that return students data will be stored in this

            test().then((res) => {
                console.log(res);
            })
            //if we do not have internet connectivity then it cannot fetch data and promise will return rejection and catch is going to execute.
            .catch((error)=>{
                console.log(error)
            })

            console.log("4 : Message");
            
//-----------making above code more shorter

            async function test1() {
                
                return (await fetch("https://jsonplaceholder.typicode.com/users")).json()
            }


            test1().then((res) => {
                console.log('this short code');
                console.log(res);
            })
            //if we do not have internet connectivity then it cannot fetch data and promise will return rejection and catch is going to execute.
            .catch((error) => {
                console.log(error)
            })


//-----------the problem here is , in this way whenever we call the test function, we always need to write catch function again and again.
//for this we will use try and catch method here.
            async function test1() {
                try{
                    return (await fetch("https://jsonplaceholder.typicode.com/users")).json()

                }catch(error){
                    console.log('now we dont require to write catch again and again');
                    console.log(error)
                }
            }

                test1().then((res) => {
                    
                    console.log(res);
                })
                

    </script>
</body>

</html>